package org.moxie.confer.proxy.crypto;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.security.GeneralSecurityException;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Cross-platform compatibility tests for ChunkedCipher.
 * Test vectors generated by TypeScript ChunkedCipher (see generate-test-vectors.ts).
 */
class ChunkedCipherTest {

  private static final String KEY = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

  // "Hello, World!" encrypted with default 64KB chunk size
  private static final String SMALL = "0100010000da486a0b25d25f5fa823ead0555256f0"
    + "1023e0057b4218d386311214ab0a7486d93b8644409ca7db054dc3135d46b3bacd2cd4789233f215d6";

  // 180-byte sequential pattern encrypted with 64-byte chunk size (3 chunks)
  private static final String THREE_CHUNKS = "01000000408eb4c0cefd8e29d7c2f80d413839a8fe"
    + "6ff7c0f2962ba076f4ac99cdc4975e9df564807f7ab41a66aef89c0f7783978191cf532677a59f63"
    + "1ff5479bd5219e7fa648fe79884a19a9f4897cb3103fd42bc65cda0644b3b0efa01b49257f8b032b"
    + "a1db257546803346b9d2acbe464fa7a01161673826299e002aa0a475d7eb3ab310a6596474622aa1"
    + "48258e01cbd36a068e23fd494ef7f5cc388054c55e796c1e4c06ad9dd3824804f5c72cc90e8976e7"
    + "da952d9264e0137368a12387e5830a1352fba1141a1943d1d1a6c35ac2ce4c5fc72e126648cdcb1c"
    + "6313707832bfcb8bf6b088fc7911b1255fa69442569f46cf68a42b45811c55f0a30683d1f84173c0"
    + "47bb0c512caac62234c204a201f73f79161bc9c4dc0e7e49";

  // --- Helpers ---

  private static byte[] hex(String s) {
    byte[] data = new byte[s.length() / 2];
    for (int i = 0; i < data.length; i++) {
      data[i] = (byte) ((Character.digit(s.charAt(2 * i), 16) << 4)
                        + Character.digit(s.charAt(2 * i + 1), 16));
    }
    return data;
  }

  private static byte[] sequentialPattern(int length) {
    byte[] data = new byte[length];
    for (int i = 0; i < length; i++) data[i] = (byte) (i % 256);
    return data;
  }

  // --- Successful decryption ---

  @Test void decryptsEmptyData() throws GeneralSecurityException {
    byte[] plaintext = new ChunkedCipher(KEY).decrypt(hex(
      "010001000077a29bedf929f8ade440956e19b4eacf"
      + "994c0d990fdcc31fd1f489bb8203d043155b3255155f8012fdbdb928"
    ));
    assertArrayEquals(new byte[0], plaintext);
  }

  @Test void decryptsSmallData() throws GeneralSecurityException {
    assertArrayEquals("Hello, World!".getBytes(), new ChunkedCipher(KEY).decrypt(hex(SMALL)));
  }

  @Test void decrypts1000BytePattern() throws GeneralSecurityException {
    byte[] plaintext = new ChunkedCipher(KEY).decrypt(hex(
      "01000100002fc605c72109251d52d5ab35449fe83a5cec15dca15f3f658d0bf49cef4f5a37f1be03"
      + "d5bf1cfb14bf7da38b4abc7704e94f5862cb30852204e01ebe35e8a0d33f1040ba326437902a09de"
      + "09f60bcb11c19e48f7942af142fdc722b1f86b371cd7b19e1edd1f7365935fc84ca954591702b2e3"
      + "0ba79ee7c087262d3c4d817ca64b440f08aaef4f88196f479d77e8f3838b9fa0223f77608a6c5f90"
      + "eda66d31a75c0836c895ad334c26323cc484f5f33296addd61d70b7337e56b672f8451799d4270c2"
      + "c5711a4bf01d8838aa50e8552cdad0a47b879ca0161ca92fbbed04a500d8f2242d3296c1f8c9bd6b"
      + "995ff94b53a08cd2fcc897978a5cdf504268a4b5e0d84422f306bd4911cd3b356e3c3634512d6817"
      + "514229e35919eb114d5726c757f8a34b5a3b5b638a2a226129ee9616f1ec1556dbe741b58515069f"
      + "50ac6c4e6fb1566d1ae48113efe87770cd2e6b2794b8121735333d4b5ae20d55f9233d989859f600"
      + "aad48528929486745f9446ee9da6f34377fa537ba56ea2d38902dde807d937cd31223d196feeced4"
      + "8369d84c8ee4b1bd120a76909faf787d635e04945a74c5d2d7065ed1db41aae32000c8f90bf38fa2"
      + "65cb329e7b845bd6b348fad933a36d919c5ee227883f44be91d25e3c9e20811d99b61b61f96b5a53"
      + "bc91932b3110ab091878d6655c29fdb805d86cbf432fcb707e1578d3391927131ec3c2ba8560e485"
      + "8600e950ea76c69ecf8f1da399b77a7c73bd3516d73198ac1f49756b52ad321502b43b6b44d30af6"
      + "66e772fc4e59659c17920ab210c243803de33667adf52cf6043e0e7fcbb2483e0a5639e937c8afef"
      + "dbb32ed8bbda4ada02f60714450495e330fa050c087440dadf8cbca5c40d3ad4ec5b13dbf0ccd6f7"
      + "163962b52a7c77b939877cc6e513814fb7f383d902f62680aac8274ef551cac57abd9779a4143d20"
      + "b97d023357969e81e4919c2d750dd66a43b9f295298153411607d7ecd912ba3e5dc4e818620ebb0d"
      + "8c8d72255abeb8ac7832ca537c47eaa07ff86eb33ad96466a853d40e84440a2d26afea1f8992c3bf"
      + "c843ef156ed327ec0de326cb61800bf6431372977cdeb22f6e19d86a1672452bfb418c8b4881c63c"
      + "e70052428764e5e2946dadc2995bc3367f48f78ea51d44963595c3d826d2cb9992d0e480f6c9ea13"
      + "5fa1ae6c33d307d9ca4e66c84c6045b44a7857b2eb35f028e8ed67eb882cc05d08ce0b23ebacf64a"
      + "93367ec6a9e04f47c58853b98c1ba5a0152ae782353a885f1c2d1cd626ac19b69460a2cec8794277"
      + "861dd78526eefb673057696e1c98959522c042e200a735623bfe7e8942925f488a6c6129d61e33b6"
      + "1ca81836184719bd417caf64bf0066da896c44ede8991a7b5abee5e1193090d3a5b5c78fa00b98e9"
      + "132fddf47f924733bc73e3115af13a28c556ad00c3f1022a1b8318ddddd4380502b4c75f6d0950b1"
      + "1e9970d2ae450db066"
    ));
    assertArrayEquals(sequentialPattern(1000), plaintext);
  }

  @Test void decryptsMultipleChunks() throws GeneralSecurityException {
    assertArrayEquals(sequentialPattern(180), new ChunkedCipher(KEY).decrypt(hex(THREE_CHUNKS)));
  }

  @Test void decryptsExactChunkBoundary() throws GeneralSecurityException {
    byte[] plaintext = new ChunkedCipher(KEY).decrypt(hex(
      "01000000409c9ecb5fee221e8ec6cf2b8a2fc3554b"
      + "8f617bee54880dc485b70d609ae4d15dff791c1291c76f0593fe1a241fb2e7914f0e9122f143a49d"
      + "d4ca20d7f1156f87247f8c5f87dfcf5f828950c4e6835111769333015dd5508a5a70f260bbe29be9"
      + "496a4dcfa00e456d10c628c8529e2e0046d0b3667206ad2bf45fb80d6e9c73d13a5f906693aadc27"
      + "bb643ab321697e256b3285f70efb935407f2c03dedd05fc30c2b8df6f398bd195e199a404b00e0ac"
      + "81c19a92d67b3b0471c9c223dc88bea6847e90b5e26aa9e1"
    ));
    byte[] expected = new byte[128];
    for (int i = 0; i < 128; i++) expected[i] = (byte) ((i * 7) % 256);
    assertArrayEquals(expected, plaintext);
  }

  // --- Tampering detection ---

  @Test void rejectsWrongKey() {
    assertThrows(GeneralSecurityException.class,
      () -> new ChunkedCipher("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB=").decrypt(hex(SMALL)));
  }

  @Test void rejectsTamperedCiphertextByte() {
    // Flipped byte at offset HEADER(21) + IV(12) + 5 = 38
    assertTampered("01000000408eb4c0cefd8e29d7c2f80d413839a8fe"
      + "6ff7c0f2962ba076f4ac99cdc4975e9df59b807f7ab41a66aef89c0f7783978191cf532677a59f63"
      + "1ff5479bd5219e7fa648fe79884a19a9f4897cb3103fd42bc65cda0644b3b0efa01b49257f8b032b"
      + "a1db257546803346b9d2acbe464fa7a01161673826299e002aa0a475d7eb3ab310a6596474622aa1"
      + "48258e01cbd36a068e23fd494ef7f5cc388054c55e796c1e4c06ad9dd3824804f5c72cc90e8976e7"
      + "da952d9264e0137368a12387e5830a1352fba1141a1943d1d1a6c35ac2ce4c5fc72e126648cdcb1c"
      + "6313707832bfcb8bf6b088fc7911b1255fa69442569f46cf68a42b45811c55f0a30683d1f84173c0"
      + "47bb0c512caac62234c204a201f73f79161bc9c4dc0e7e49");
  }

  @Test void rejectsTamperedFileId() {
    // Flipped byte at offset 10 (within file_id)
    assertTampered("01000000408eb4c0cefd7129d7c2f80d413839a8fe"
      + "6ff7c0f2962ba076f4ac99cdc4975e9df564807f7ab41a66aef89c0f7783978191cf532677a59f63"
      + "1ff5479bd5219e7fa648fe79884a19a9f4897cb3103fd42bc65cda0644b3b0efa01b49257f8b032b"
      + "a1db257546803346b9d2acbe464fa7a01161673826299e002aa0a475d7eb3ab310a6596474622aa1"
      + "48258e01cbd36a068e23fd494ef7f5cc388054c55e796c1e4c06ad9dd3824804f5c72cc90e8976e7"
      + "da952d9264e0137368a12387e5830a1352fba1141a1943d1d1a6c35ac2ce4c5fc72e126648cdcb1c"
      + "6313707832bfcb8bf6b088fc7911b1255fa69442569f46cf68a42b45811c55f0a30683d1f84173c0"
      + "47bb0c512caac62234c204a201f73f79161bc9c4dc0e7e49");
  }

  @Test void rejectsTamperedChunkSize() {
    // Flipped bit in chunk size field (byte 2)
    assertTampered("01000100408eb4c0cefd8e29d7c2f80d413839a8fe"
      + "6ff7c0f2962ba076f4ac99cdc4975e9df564807f7ab41a66aef89c0f7783978191cf532677a59f63"
      + "1ff5479bd5219e7fa648fe79884a19a9f4897cb3103fd42bc65cda0644b3b0efa01b49257f8b032b"
      + "a1db257546803346b9d2acbe464fa7a01161673826299e002aa0a475d7eb3ab310a6596474622aa1"
      + "48258e01cbd36a068e23fd494ef7f5cc388054c55e796c1e4c06ad9dd3824804f5c72cc90e8976e7"
      + "da952d9264e0137368a12387e5830a1352fba1141a1943d1d1a6c35ac2ce4c5fc72e126648cdcb1c"
      + "6313707832bfcb8bf6b088fc7911b1255fa69442569f46cf68a42b45811c55f0a30683d1f84173c0"
      + "47bb0c512caac62234c204a201f73f79161bc9c4dc0e7e49");
  }

  @Test void rejectsTamperedVersion() {
    assertTampered("99000000408eb4c0cefd8e29d7c2f80d413839a8fe"
      + "6ff7c0f2962ba076f4ac99cdc4975e9df564807f7ab41a66aef89c0f7783978191cf532677a59f63"
      + "1ff5479bd5219e7fa648fe79884a19a9f4897cb3103fd42bc65cda0644b3b0efa01b49257f8b032b"
      + "a1db257546803346b9d2acbe464fa7a01161673826299e002aa0a475d7eb3ab310a6596474622aa1"
      + "48258e01cbd36a068e23fd494ef7f5cc388054c55e796c1e4c06ad9dd3824804f5c72cc90e8976e7"
      + "da952d9264e0137368a12387e5830a1352fba1141a1943d1d1a6c35ac2ce4c5fc72e126648cdcb1c"
      + "6313707832bfcb8bf6b088fc7911b1255fa69442569f46cf68a42b45811c55f0a30683d1f84173c0"
      + "47bb0c512caac62234c204a201f73f79161bc9c4dc0e7e49");
  }

  @Test void rejectsReorderedChunks() {
    // Chunks 0 and 1 swapped
    assertTampered("01000000408eb4c0cefd8e29d7c2f80d413839a8fe"
      + "464fa7a01161673826299e002aa0a475d7eb3ab310a6596474622aa148258e01cbd36a068e23fd49"
      + "4ef7f5cc388054c55e796c1e4c06ad9dd3824804f5c72cc90e8976e7da952d9264e0137368a12387"
      + "e5830a1352fba1141a1943d16ff7c0f2962ba076f4ac99cdc4975e9df564807f7ab41a66aef89c0f"
      + "7783978191cf532677a59f631ff5479bd5219e7fa648fe79884a19a9f4897cb3103fd42bc65cda06"
      + "44b3b0efa01b49257f8b032ba1db257546803346b9d2acbed1a6c35ac2ce4c5fc72e126648cdcb1c"
      + "6313707832bfcb8bf6b088fc7911b1255fa69442569f46cf68a42b45811c55f0a30683d1f84173c0"
      + "47bb0c512caac62234c204a201f73f79161bc9c4dc0e7e49");
  }

  @Test void rejectsTruncatedLastChunk() {
    // Only first 2 of 3 encrypted chunks
    assertTampered("01000000408eb4c0cefd8e29d7c2f80d413839a8fe"
      + "6ff7c0f2962ba076f4ac99cdc4975e9df564807f7ab41a66aef89c0f7783978191cf532677a59f63"
      + "1ff5479bd5219e7fa648fe79884a19a9f4897cb3103fd42bc65cda0644b3b0efa01b49257f8b032b"
      + "a1db257546803346b9d2acbe464fa7a01161673826299e002aa0a475d7eb3ab310a6596474622aa1"
      + "48258e01cbd36a068e23fd494ef7f5cc388054c55e796c1e4c06ad9dd3824804f5c72cc90e8976e7"
      + "da952d9264e0137368a12387e5830a1352fba1141a1943d1");
  }

  @Test void rejectsHeaderOnly() {
    assertTampered("01000000408eb4c0cefd8e29d7c2f80d413839a8fe");
  }

  @Test void rejectsCrossFileChunks() {
    // Header from one encryption, chunks from a different encryption
    assertTampered("01000000408eb4c0cefd8e29d7c2f80d413839a8fe"
      + "9165e0ddffa21d0edcb2ec7187afdfcf44ffe79ae0623e552213a5b821e94d0d22e15f3b313df3e3"
      + "235064c109c3e7161b56382fbace951733a7cbfa8d0bad8f568903cea845091a3207ad28e7ee675e"
      + "d67e66e1a3e1788c6403673ee2f9b194dba9169aeba147a4b4895da7614e592390006d8b70d5f475"
      + "2ceeab081a04e5d088ea595db6488bba2bf57ab02af39f090aa342c41867f7a77b049d1841b4c6eb"
      + "313af7528ecc87a4eaf6cf3f9d4296e30b64cda75176fabe4f9160edd58b09566d0f184a05601da7"
      + "bcd85b7926b3f4ceecc8a841a3140bc174b8ea20c87929f56d61421bb5ce9b7a2b41547429a2da9b"
      + "5b9227e6a7224c5a2a1716f43dd42dcff2c8a7262dba0071");
  }

  @Test void rejectsTooShortData() {
    assertTampered("00000000000000000000");
  }

  @Test void rejectsChunkTooShort() {
    assertTampered("01000000408eb4c0cefd8e29d7c2f80d413839a8fe0000000000");
  }

  private static void assertTampered(String ciphertextHex) {
    assertThrows(GeneralSecurityException.class,
      () -> new ChunkedCipher(KEY).decrypt(hex(ciphertextHex)));
  }

  // --- Streaming decryption ---

  @Test void streamingMatchesOneShot() throws GeneralSecurityException {
    byte[] ciphertext = hex(THREE_CHUNKS);
    ChunkedCipher cipher = new ChunkedCipher(KEY);
    ByteArrayOutputStream out = new ByteArrayOutputStream();

    int piece = 37; // deliberately misaligned
    for (int i = 0; i < ciphertext.length; i += piece) {
      int end = Math.min(i + piece, ciphertext.length);
      byte[] chunk = Arrays.copyOfRange(ciphertext, i, end);
      out.writeBytes(end >= ciphertext.length ? cipher.doFinal(chunk) : cipher.update(chunk));
    }

    assertArrayEquals(sequentialPattern(180), out.toByteArray());
  }

  @Test void streamingWithHeaderSplitAcrossUpdates() throws GeneralSecurityException {
    byte[] ct = hex(SMALL);
    ChunkedCipher cipher = new ChunkedCipher(KEY);
    ByteArrayOutputStream out = new ByteArrayOutputStream();

    out.writeBytes(cipher.update(Arrays.copyOfRange(ct, 0, 10)));   // partial header
    out.writeBytes(cipher.update(Arrays.copyOfRange(ct, 10, 25)));  // rest of header + chunk start
    out.writeBytes(cipher.doFinal(Arrays.copyOfRange(ct, 25, ct.length)));

    assertArrayEquals("Hello, World!".getBytes(), out.toByteArray());
  }
}
